runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: git config user.name "${{github.actor}}"
      shell: bash
    - run: git config user.email "${{github.actor}}@users.noreply.github.com"
      shell: bash

    - run: npx standard-version
      shell: bash

    - run: git push origin HEAD --follow-tags
      shell: bash

name: release

branding:
  color: blue
  icon: box

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.7.8
