name: release

branding:
  color: blue
  icon: box

inputs:
  AWS_ACCESS_KEY_ID_DEV: { description: dev aws access key id, required: true }

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.7.8
        with:
          release-type: node
          token: ${{inputs.AWS_ACCESS_KEY_ID_DEV}}
