name: release
description: "Automate release PRs with release-please"

branding:
  color: blue
  icon: box

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.7.8
        with:
          release-type: node
          token: ${{secrets.GITHUB_TOKEN}}
