name: release with release-please
description: "release with release-please"

branding:
  color: blue
  icon: box

inputs:
  GITHUB_TOKEN: { description: github token, required: true }

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

runs:
  using: composite
  steps:
    - uses: google-github-actions/release-please-action@v3.7.8
      with:
        release-type: node
        token: ${{inputs.GITHUB_TOKEN}}
